# Generated by Django 3.0.2 on 2020-01-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_constructor', '0002_auto_20200117_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='price',
        ),
    ]
